version: "3.8"

services:
  test-db:
    image: postgres:13.2-alpine
    container_name: test-db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test